languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Ahmed Aboelnaga"
copyright = "Ahmed Aboelnaga"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
   description = "Personal portfolio website of Ahmed aboelnaga"

[params.author]
   name = "Ahmed Aboelnaga"
   image = "img/profile.jpg"
   headline = "Aspiring AI/ML Engineer | Passionate About Software Development & Problem-Solving"
   bio = "I'm Ahmed, a computer science student specializing in AI with skills in Python, machine learning, data analysis, statistics, and algorithms. I’m passionate about building AI-driven solutions and continuously improving my expertise in data science and ML. 🚀"
   links = [
     { email = "ahmedgaboelnaga@gmail.com" },
  #   { link = "https://www.behance.net/ahmedgaboelnaga" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/ahmedgaboelnaga" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://www.instagram.com/ahmedgaboelnaga/" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://www.linkedin.com/in/ahmedgaboelnaga/" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/ahmedgaboelnaga" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
     { whatsapp = "https://wa.me/+201289720964" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
     { behance = "https://www.behance.net/ahmedgaboelnaga"},
   ]